WIP.
this introduces the metacoq types but still not deriving.

error is :

-*- mode: compilation; default-directory: "/mnt/data1/2023/07/22/morpheus-graphql/examples/scotty/src/Server/Mythology/" -*-
Compilation started at Sun Jul 23 09:47:23

stack build
morpheus-graphql-examples-scotty> build (exe)
Preprocessing executable 'scotty-server' for morpheus-graphql-examples-scotty-0.1.0..
Building executable 'scotty-server' for morpheus-graphql-examples-scotty-0.1.0..
[12 of 18] Compiling Server.Subscription.SimpleSubscription [Server.Mythology.Character changed]
[15 of 18] Compiling Server.Mythology.API

/mnt/data1/2023/07/22/morpheus-graphql/examples/scotty/src/Server/Mythology/API.hs:112:7: error:
    • No instance for (morpheus-graphql-server-0.27.3:Data.Morpheus.Server.Deriving.Utils.GRep.GRep
                         GQLType
                         (morpheus-graphql-server-0.27.3:Data.Morpheus.Server.Types.GQLType.GQLResolver
                            (morpheus-graphql-app-0.27.3:Data.Morpheus.App.Internal.Resolving.Resolver.Resolver
                               morpheus-graphql-core-0.27.3:Data.Morpheus.Types.Internal.AST.OperationType.QUERY
                               ()
                               IO))
                         (morpheus-graphql-app-0.27.3:Data.Morpheus.App.Internal.Resolving.Resolver.Resolver
                            morpheus-graphql-core-0.27.3:Data.Morpheus.Types.Internal.AST.OperationType.QUERY
                            ()
                            IO
                            (morpheus-graphql-app-0.27.3:Data.Morpheus.App.Internal.Resolving.Types.ResolverValue
                               (morpheus-graphql-app-0.27.3:Data.Morpheus.App.Internal.Resolving.Resolver.Resolver
                                  morpheus-graphql-core-0.27.3:Data.Morpheus.Types.Internal.AST.OperationType.QUERY
                                  ()
                                  IO)))
                         (GHC.Generics.Rep (Prod Global_env Term)))
        arising from a use of ‘deriveApp’
    • In the expression: deriveApp rootResolver
      In an equation for ‘app’: app = deriveApp rootResolver
    |
112 | app = deriveApp rootResolver
    |       ^^^^^^^^^